#############################################################
#The name at the top of the inventory and on the last row of enderchests
#############################################################
Inventory:
 
  first_ec_name: '&2Servername enderchest #1'
  first_ec_name_edit: '&2Servername enderchest #1 Edit'

  second_ec_name: '&2Servername EnderChest #2'
  second_ec_name_edit: '&2Servername enderchest #2 Edit'

  third_ec_name: '&2Servername EnderChest #3'
  third_ec_name_edit: '&2Servername enderchest #3 Edit'
  
  fourth_ec_name: '&2Servername EnderChest #4'
  fourth_ec_name_edit: '&2Servername enderchest #4 Edit'
  
  fifth_ec_name: '&2Servername EnderChest #5'
  fifth_ec_name_edit: '&2Servername enderchest #5 Edit'

#############################################################
#When the console tries to use /enderchest it will throw this error message
#############################################################
Command:

  ConsoleSender: '&cConsole cant use this command'

#############################################################
#MySQL Database Connection info
#############################################################
MySQL:
  host: '127.0.0.1'
  port: 3306
  database: 'minecraft'
  username: 'root'
  password: 'password'
#The table will be called CustomEnderChest in the database